baseURL = 'https://codesutra.net/sethu'
languageCode = 'en-us'
title = 'Draft Sethu Website'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Programs'
pageRef = '/Programs'
weight = 20

[[menus.main]]
name = 'Child Development Clinic'
pageRef = '/programs/child-development-clinic'
weight = 210
parent = 'Programs'

[[menus.main]]
name = 'Inclusive Education'
pageRef = '/programs/inclusive-education'
weight = 220
parent = 'Programs'

[[menus.main]]
name = 'Autism Intervention'
pageRef = '/programs/autism-intervention'
weight = 230
parent = 'Programs'

[[menus.main]]
name = 'Capacities'
pageRef = '/capacities'
weight = 30

[[menus.main]]
name = 'Research'
pageRef = '/capacities/research'
weight = 330
parent = 'Capacities'

[[menus.main]]
name = 'Training'
pageRef = '/capacities/training'
weight = 310
parent = 'Capacities'

[[menus.main]]
name = 'Advocacy'
pageRef = '/capacities/advocacy'
weight = 320
parent = 'Capacities'

[[menus.main]]
name = 'Diary'
pageRef = '/diary'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 50

[[menus.main]]
name = 'Our Story'
pageRef = '/about/our-story'
weight = 510
parent = 'About'

[[menus.main]]
name = 'Awards'
pageRef = '/about/awards'
weight = 520
parent = 'About'

[[menus.main]]
name = 'Team'
pageRef = '/about/team'
weight = 530
parent = 'About'

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
