baseURL = 'https://codesutra.net/sethu'
languageCode = 'en-us'
title = 'Draft Sethu Website'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Programs'
pageRef = '/Programs'
weight = 20

[[menus.main]]
name = 'Child Development Clinic'
pageRef = '/programs/child-development-clinic'
weight = 210
parent = 'Programs'

[[menus.main]]
name = 'Inclusive Education'
pageRef = '/programs/inclusive-education'
weight = 220
parent = 'Programs'

[[menus.main]]
name = 'Autism Intervention'
pageRef = '/programs/autism-intervention'
weight = 230
parent = 'Programs'

[[menus.main]]
name = 'Gnyandeep'
pageRef = '/programs/gnyandeep'
weight = 240
parent = 'Programs'

[[menus.main]]
name = 'Resources'
pageRef = '/resources'
weight = 30

[[menus.main]]
name = 'Training'
pageRef = '/resources/training'
weight = 320
parent = 'Resources'

[[menus.main]]
name = 'Research'
pageRef = '/resources/research'
weight = 330
parent = 'Resources'

[[menus.main]]
name = 'Advocacy'
pageRef = '/resources/advocacy'
weight = 340
parent = 'Resources'

[[menus.main]]
name = 'Diary'
pageRef = '/diary'
weight = 40

[[menus.main]]
name = 'Careers'
pageRef = '/careers'
weight = 50

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 60

[[menus.main]]
name = 'Our Story'
pageRef = '/about/our-story'
weight = 610
parent = 'About'

[[menus.main]]
name = 'Policies'
pageRef = '/about/policies'
weight = 620
parent = 'About'

[[menus.main]]
name = 'Awards'
pageRef = '/about/awards'
weight = 630
parent = 'About'

[[menus.main]]
name = 'Team'
pageRef = '/about/team'
weight = 640
parent = 'About'

[[menus.main]]
name = 'Trustees'
pageRef = '/about/trustees'
weight = 650
parent = 'About'

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 70

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
